### ISSUE TITLE
Crashing on 1.16.1 server

### ISSUE THREAD

**Issue by Processhf** [Globox1997/MobZ#12]
[04-07-2020 18:34:40] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mobz'!
[04-07-2020 18:34:40] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at net.minecraft.server.Main.main(Main.java:125) [intermediary-server.jar:?]
[04-07-2020 18:34:40] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
[04-07-2020 18:34:40] Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraft/class_638
[04-07-2020 18:34:40] at net.mobz.Items.Item.Sbow.<init>(Sbow.java:21) ~[mobz-2.4.0.jar:?]
[04-07-2020 18:34:40] at net.mobz.Inits.Iteminit.<clinit>(Iteminit.java:23) ~[mobz-2.4.0.jar:?]
[04-07-2020 18:34:40] at net.mobz.glomod.onInitialize(glomod.java:15) ~[mobz-2.4.0.jar:?]
[04-07-2020 18:34:40] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
[04-07-2020 18:34:40] ... 17 more
[04-07-2020 18:34:40] Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
[04-07-2020 18:34:40] at net.mobz.Items.Item.Sbow.<init>(Sbow.java:21) ~[mobz-2.4.0.jar:?]
[04-07-2020 18:34:40] at net.mobz.Inits.Iteminit.<clinit>(Iteminit.java:23) ~[mobz-2.4.0.jar:?]
[04-07-2020 18:34:40] at net.mobz.glomod.onInitialize(glomod.java:15) ~[mobz-2.4.0.jar:?]
[04-07-2020 18:34:40] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
[04-07-2020 18:34:40] ... 17 more
[04-07-2020 18:34:40] Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
[04-07-2020 18:34:40] at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-server-launch.jar:?]
[04-07-2020 18:34:40] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
[04-07-2020 18:34:40] at net.mobz.Items.Item.Sbow.<init>(Sbow.java:21) ~[mobz-2.4.0.jar:?]
[04-07-2020 18:34:40] at net.mobz.Inits.Iteminit.<clinit>(Iteminit.java:23) ~[mobz-2.4.0.jar:?]
[04-07-2020 18:34:40] at net.mobz.glomod.onInitialize(glomod.java:15) ~[mobz-2.4.0.jar:?]
[04-07-2020 18:34:40] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
[04-07-2020 18:34:40] ... 17 more

**Comment by Globox1997** [comment]
I think I know exactly why it´s crashing the game (same as in my other mods) but I have to wait for fabric until they add something specific: [issue](https://github.com/FabricMC/fabric/issues/856), so for now almost all of my mods are working only in singleplayer

**Comment by Globox1997** [comment]
fixed it
