### ISSUE TITLE
Crash on 1.16.1 when using the pillager staff.

### ISSUE THREAD

**Issue by ghost** [Globox1997/MobZ#15]
Log: https://pastebin.com/amdUe7ZL

**Comment by Globox1997** [comment]
should be fixed in 2.4.3

**Comment by ghost** [comment]
I've tested 2.4.3, the problem seems to persist
https://pastebin.com/s3BDAmhn

**Comment by allanf181** [comment]
https://github.com/Globox1997/MobZ/blob/371ee01aa74bfb79368c22b5caf5824c1883d9b1/src/main/java/net/mobz/Items/Item/Pillagerstaff.java#L104

addParticle is a ClientWorld method, crashes on server

**Comment by linzexin022** [comment]
The same problem. Here's the game log:

[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_1937.method_8466(net.minecraft.class_2394, boolean, double, double, double, double, double, double)'
	at net.mobz.Items.Item.Pillagerstaff.method_7836(Pillagerstaff.java:104) ~[mobz-2.4.3.jar:?]
	at net.minecraft.class_1799.method_7913(class_1799.java:225) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14256(class_3225.java:283) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12065(class_3244.java:1012) ~[intermediary-server.jar:?]
	at net.minecraft.class_2886.method_12550(class_2886.java:31) ~[intermediary-server.jar:?]
	at net.minecraft.class_2886.method_11054(class_2886.java:9) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
