### ISSUE TITLE
crash upon breeding 2 golden chickens

### ISSUE THREAD

**Issue by Nathan22211** [Globox1997/MobZ#2]
`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/19/19 3:11 AM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.class_1428 cannot be cast to net.mobz.Entity.GChicken
	at net.mobz.Entity.GChicken.method_6471(GChicken.java:116)
	at net.mobz.Entity.GChicken.method_5613(GChicken.java:169)
	at net.minecraft.class_1341.method_6249(class_1341.java:85)
	at net.minecraft.class_1341.method_6268(class_1341.java:66)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355$$Lambda$4250/280564355.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.class_1355.method_6275(class_1355.java:80)
	at net.minecraft.class_1308.method_6023(class_1308.java:623)
	at net.minecraft.class_1309.method_6007(class_1309.java:2266)
	at net.minecraft.class_1308.method_6007(class_1308.java:487)
	at net.minecraft.class_1296.method_6007(class_1296.java:140)
	at net.minecraft.class_1429.method_6007(class_1429.java:44)
	at net.minecraft.class_1428.method_6007(class_1428.java:80)
	at net.mobz.Entity.GChicken.method_6007(GChicken.java:72)
	at net.minecraft.class_1309.method_5773(class_1309.java:2111)
	at net.minecraft.class_1308.method_5773(class_1308.java:294)
	at net.minecraft.class_3218.method_18762(class_3218.java:583)
	at net.minecraft.class_3218$$Lambda$4236/286587493.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:675)
	at net.minecraft.class_3218.method_18765(class_3218.java:386)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:835)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774)
	at net.minecraft.class_1132.method_3748(class_1132.java:128)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.mobz.Entity.GChicken.method_6471(GChicken.java:116)
	at net.mobz.Entity.GChicken.method_5613(GChicken.java:169)
	at net.minecraft.class_1341.method_6249(class_1341.java:85)
	at net.minecraft.class_1341.method_6268(class_1341.java:66)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355$$Lambda$4250/280564355.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.class_1355.method_6275(class_1355.java:80)
	at net.minecraft.class_1308.method_6023(class_1308.java:623)
	at net.minecraft.class_1309.method_6007(class_1309.java:2266)
	at net.minecraft.class_1308.method_6007(class_1308.java:487)
	at net.minecraft.class_1296.method_6007(class_1296.java:140)
	at net.minecraft.class_1429.method_6007(class_1429.java:44)
	at net.minecraft.class_1428.method_6007(class_1428.java:80)
	at net.mobz.Entity.GChicken.method_6007(GChicken.java:72)
	at net.minecraft.class_1309.method_5773(class_1309.java:2111)
	at net.minecraft.class_1308.method_5773(class_1308.java:294)
	at net.minecraft.class_3218.method_18762(class_3218.java:583)
	at net.minecraft.class_3218$$Lambda$4236/286587493.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: mobz:gchicken_entity (net.mobz.Entity.GChicken)
	Entity ID: 1628
	Entity Name: Golden Chicken
	Entity's Exact location: 33.35, 64.00, -126.60
	Entity's Block location: World: (33,64,-127), Chunk: (at 1,4,1 in 2,-8; contains blocks 32,0,-128 to 47,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:675)
	at net.minecraft.class_3218.method_18765(class_3218.java:386)

-- Affected level --
Details:
	All players: 1 total; [class_3222['nathan2221'/289, l='New World', x=33.67, y=64.00, z=-129.16]]
	Chunk stats: ServerChunkCache: 2791
	Level dimension: minecraft:overworld
	Level name: New World
	Level seed: 6813477521366500955
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (64,72,-63), Chunk: (at 0,4,1 in 4,-4; contains blocks 64,0,-64 to 79,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 3163 game time, 3163 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 142101 (now: false), thunder time: 58120 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:835)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774)
	at net.minecraft.class_1132.method_3748(class_1132.java:128)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2138416752 bytes (2039 MB) / 7985954816 bytes (7616 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.5.0+1.14.4
		allure: Allure 1.1.5
		amethystmod: Amethyst Mod 1.2.0
		aquarius: Aquarius 1.4.0+1.14.4
		artifice: Artifice 0.3.5
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		autojson: Auto Json 1.14.4-1.1.0
		bambootweaks: Bamboo Tweaks 1.14.4-1.1.0
		bark: Tree Bark 1.1.0
		battle-towers: Battle Towers 1.1.2
		beachslimes: Beach Slimes 1.3.0+mc1.14.4
		berrysmod: Berry's Mod 1.1.3
		block_factory: Block Factory 0.3.0
		blockus: Blockus 1.2.0
		blue_endless_jankson: jankson +
		chunkactivator: Chunk Activator 1.2.0+mc1.14.4
		clippys_tippies: Clippie's Tippies Â® 1.0.0
		cloth: Cloth Events 0.6.0
		cloth-config: Cloth Config 0.2.4+build.17
		cloth-config2: Cloth Config v2 1.1.1
		composableautomation: Composable Automation 0.6.0+mc1.14.4
		cookies: Cookies 1.14.4-1.0.0.1-universal
		cotton: Cotton 1.0.0-rc.3
		cotton-cauldron: Cotton Cauldron 1.0.0-rc.1
		cotton-client-commands: Cotton Client Commands 0.4.2+1.14.3-SNAPSHOT
		cotton-commons: Cotton Commons 1.0.0-rc.3
		cotton-config: Cotton Config 1.0.0-rc.1
		cotton-datapack: Cotton Datapack 1.0.0-rc.1
		cotton-logging: Cotton Logging 1.0.0-rc.1
		cotton-player-events: Cotton Player Events 1.0.0-rc.2
		cotton-resources: Cotton Resources 1.4.1+1.14.4
		crafty: Crafty 0.3.3+1.14.1
		creativebuttonmover: Creative Button Mover 0.1.1+1.14.4
		creeperspores: Creeper Spores 1.2.1
		customrecord: Custom Records 1.0.2
		dynagear: DynaGear 1.3.1+1.14.4
		eggsplus: Eggs Plus 1.1.0
		emerald: Emerald tools 1.8.1
		enchantedtooltips: Enchanted ToolTips 1.1.0
		endreborn: End: Rebellion 1.0
		ep-addon: Extra Pieces Addon 1.0.2
		expandedstorage: ExpandedStorage 3.6.29+1.14.4
		extradiscs: ExtraDiscs 1.1.0+build.6
		extradoors: ExtraDoors 1.2.0
		extrapieces: Extra Pieces 2.8.3
		fabric: Fabric API 0.3.3+build.234-1.14
		fabric-api-base: fabric-api-base 0.1.0+5914746342
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.1+591e97ae42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-language-kotlin: Fabric Language Kotlin 1.3.50+build.1
		fabric-language-scala: Fabric Language Scala 0.2.0.9
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.0+591e97ae42
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.1.1+591e97ae42
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.0+591e97ae42
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabricdrawer: Fabric Drawer 1.1.1
		fabricloader: Fabric Loader 0.6.2+build.166
		faeriefire: Faerie Fire 1.0.1
		fiber2cloth: Fiber To Cloth 1.1.0
		flax: Flax 1.0.0
		function_api: Function API 1.2.2
		glassential: Glassential 1.14.4-1.1.0
		grindstone_books: Grindstone Books 1.0.0
		handystructures: Handy Structures 1.0.3
		hardstone_1730: Hardstone Mod 1.0.7
		heartofthecauldron: Heart of the Cauldron 1.1.0
		illuminations: Illuminations 0.3.0
		infinityfix: Infinity Fix 1.1.0
		jankson: Jankson 1.0.0+j1.1.2
		jargm: Just Another Redstone Gate Mod 1.0.1
		ladderapi: Ladder API 1.14.4-1.1.0
		libblockattributes_core: LibBlockAttributes (Core) 0.4.10
		libblockattributes_items: LibBlockAttributes (Items) 0.4.10
		libcd: LibCapableData 1.3.4+1.14.4
		libgui: LibGui 1.3.2
		loot_editor: LootEditor 1.0.0-SNAPSHOT
		luminiferous_uplands: Luminiferous Uplands 1.1.1
		me_zeroeightsix_fiber: fiber 0.6.0-7
		minecraft: Minecraft 1.14.4
		miners_horizon: Miner's Horizon 1.5.0
		ml3lib: ML3 Library 1.1.1
		mm: Manningham Mills 1.7
		mobz: MobZ 1.7.4
		mooblooms: Mooblooms 1.0.1
		moreberries: More Berries 1.2.1
		mycraft: My Craft 1.2.4
		nbtcrafting: NBT Crafting 1.2.4+1.14.4
		netherthings: Nether Things 1.2.0
		nodami: No Damage Immunity (NoDamI) 1.14.4-0.2-fabric
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.50
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-runtime: kotlinx-serialization-runtime 0.12.0
		paintz: PaintZ 1.0
		pathsuggestion: Path Suggestion 0.2.0
		proletarian: Proletarian 0.10.0+mc1.14.4
		redstonebits: Redstone Bits 1.0.4+mc1.14.1
		redstoneutils: Redstone Utils 1.14.4-1.0.0
		reinstorage: Reinforced Storage 1.1.2
		roughlyenoughitems: Roughly Enough Items 3.1.2+build.12
		sde: Stackable Damage Enchants 1.0.1
		simplevoidworld: Simple Void World 1.0.0
		smartermending: Smarter Mending 1.1.0
		spatialcrafting: Spatial Crafting 1.2.0
		statement: Statement 1.0.0+1.14.4
		staticdata: Static Data 1.0.0
		stoneextended: Stone Extended 1.0.4
		stuffz: StuffZ 1.0.0
		terraform: Terraform 1.1.8+build.15
		terrestria: Terrestria 1.0.11+build.40
		toughglass: Tough Glass 1.0.0
		towelette: Towelette 2.0.1+1.14.4
		traverse: Traverse 2.0.8+build.26
		trumpet-skeleton: Trumpet Skeleton 1.1.0
		tsb: Trapped Shulker Boxes 1.0.4
		vanilla-hammers: Vanilla Hammers 1.6.3
		vanilla-toolsets: Vanilla Toolsets 1.2.1
		vanillaecxavators: Vanilla Excavators 1.0.2
		variablepaxels: VariablePaxels 1.14.4-1.0.1
		verticalredstone: Vertical Redstone 1.0.1
		vmulti: Vanilla Multiblock API 1.0.1+1.14.4
		wildworld: Wild World 1.2.0
		woodmill: Woodmill 1.0.0
		working-scheduler: Working Scheduler 1.1.0
		zmod: AppleZ 1.3.0
	Player Count: 1 / 8; [class_3222['nathan2221'/289, l='New World', x=33.67, y=64.00, z=-129.16]]
	Data Packs: vanilla, extrapieces:ep_data, dynagear:dynagear_data, fabric/adorn, fabric/allure, fabric/amethystmod, fabric/aquarius, fabric/bambootweaks, fabric/bark, fabric/battle-towers, fabric/beachslimes, fabric/berrysmod, fabric/blockus, fabric/chunkactivator, fabric/composableautomation, fabric/cookies, fabric/cotton-commons, fabric/cotton-resources, fabric/creeperspores, fabric/eggsplus, fabric/emerald, fabric/endreborn, fabric/expandedstorage, fabric/extradiscs, fabric/extradoors, fabric/fabric-mining-levels-v0, fabric/faeriefire, fabric/flax, fabric/function_api, fabric/glassential, fabric/handystructures, fabric/hardstone_1730, fabric/heartofthecauldron, fabric/illuminations (incompatible), fabric/jargm, fabric/libcd, fabric/luminiferous_uplands, fabric/mobz, fabric/mooblooms, fabric/moreberries, fabric/mycraft, fabric/netherthings, fabric/paintz, fabric/proletarian, fabric/redstonebits, fabric/redstoneutils, fabric/reinstorage, fabric/simplevoidworld, fabric/spatialcrafting, fabric/stoneextended, fabric/stuffz, fabric/terrestria, fabric/toughglass, fabric/towelette, fabric/traverse, fabric/trumpet-skeleton, fabric/tsb, fabric/vanilla-hammers, fabric/vanilla-toolsets, fabric/vanillaecxavators, fabric/variablepaxels, fabric/verticalredstone, fabric/vmulti, fabric/wildworld, fabric/woodmill, fabric/zmod, global/Datapack-Utilities-master (incompatible), global/DatapackUtilities_v2.0.1a.zip (incompatible), global/Fancier+Mansions+v1.0.zip (incompatible), global/Mechanization_v2.1.0c.zip (incompatible), global/More Bosses (incompatible), global/Pushable+Tile+Entities.zip (incompatible), global/better_spiders.zip, global/better_wanderers (1).zip (incompatible), global/cactus gear (incompatible), global/cotton_generated (incompatible), global/magma gear (incompatible), global/phi_core.zip, global/phi_rng.zip, global/wirelessredstonedeluxe (incompatible), global/wood_age_data (incompatible), loot_editor/inject
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'`

this will likely happen with any of your mobs that extend mobs that can breed

**Comment by Globox1997** [comment]
Thanks for notification, I'm looking forward to fix this

**Comment by Globox1997** [comment]
fixed it
